before_script:
  - composer install

cache:
  paths:
  - vendor/

stages:
  - test

Code Style:
  stage: test
  script:
    - vendor/bin/phpcs --standard=PSR2 --colors -pn src/

Mess Detector:
  stage: test
  allow_failure: true
  script:
    - vendor/bin/phpmd src text cleancode,codesize,controversial,design,naming --suffixes php

PHP Stan:
  stage: test
  script:
    - vendor/bin/phpstan analyse --level max -c phpstan.neon src
