FROM composer as composer-builder

ENV APP_ENV dev

COPY . /app/
COPY .env.production /app/.env
WORKDIR /app
RUN composer install --no-dev -o

# Use a smaller image for production
FROM php:7.2-fpm-alpine3.6

RUN docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" opcache pdo_mysql && \
  touch /usr/local/etc/php/php.ini && \
  echo "memory_limit = 1024M" >> /usr/local/etc/php/php.ini

COPY --from=composer-builder /app /var/www/html
RUN rm -rf /var/www/html/var/cache/* && \
  /var/www/html/bin/console --env="dev" cache:clear && \
  /var/www/html/bin/console --env="dev" cache:warmup  && \
  chmod 777 -R /var/www/html/var/cache/
