version: '2'

services:
    app:
        build:
             context: ./
             dockerfile: Dockerfile
        restart: 'no'
        volumes:
            - /var/log/database-dump-storage:/app/var/log/
